### PR TITLE
💚 Reduced CI builds

### PR DESCRIPTION
**Pull request by buttercrab**
- Remove CI for Windows and macOS

### CODE REVIEW

**Review by utilForever — APPROVED** [review]
Good to go! 🚀

**Comment by utilForever** [comment]
bors try

**Comment by utilForever** [comment]
bors try

**Review by utilForever — APPROVED** [review]
Good to go! 🚀

**Comment by utilForever** [comment]
bors try

**Review by sboh1214 — APPROVED** [review]
Redundant green heart

**Pull request merged**
