### PR TITLE
✨ Made Pipe & PipeFactory

### PR DESCRIPTION
**Pull request by buttercrab**
- This helps to make middleware like logger
- Made PipeFactory for building with inner Pipe
- Added example for Pipe
- Added documentation for Pipe
- Preparation for supporting QUIC

### CODE REVIEW

**Review by minchurl — COMMENTED** [review]
pipe.rs is really interesting! good.

**Review by minchurl — APPROVED** [review]
pipe.rs is interesting!

**Review by utilForever — APPROVED** [review]
Looks good. You should improve code coverage in the future. 😉

**Pull request merged**
