### PR TITLE
Add handler & layer related traits & structs

### PR DESCRIPTION
**Pull request by buttercrab**
now you can make handler & layer from functions

<details><summary>before</summary>
<p>

```rust
// Factory of Echo.
pub struct EchoFactory;

// Pipe that sends the message to next as is
pub struct Echo<T, P>
where
    P: Handler<T>,
{
    prev: P,
    _marker: PhantomData<T>,
}

impl<T, P> Layer<T, P> for EchoFactory
where
    P: Handler<T>,
    P::Future: 'static,
{
    type Next = T;
    type Error = P::Error;
    type Handler = Echo<T, P>;
    type InitError = ();
    type Future = Ready<Result<Self::Handler, Self::InitError>>;

    fn new_handler(&self, prev: P) -> Self::Future {
        ok(Echo {
            prev,
            _marker: PhantomData::default(),
        })
    }
}

impl<T, P> Handler<T> for Echo<T, P>
where
    P: Handler<T>,
    P::Future: 'static,
{
    type Error = P::Error;
    type Future = LocalBoxFuture<'static, Result<(), Self::Error>>;

    fn call(&self, msg: T) -> Self::Future {
        let prev_call = self.prev.call(msg);
        // this would act as same future of previous pipe,
        // but type of `Ok` is `()`
        Box::pin(async move {
            prev_call.await?;
            Ok(())
        })
    }
}

// print to stdout that got
pub struct Print;
impl<S> Handler<S> for Print
where
    S: Display,
{
    type Error = ();
    type Future = Ready<Result<(), Self::Error>>;

    // just calls `print!`
    // then just be ready
    fn call(&self, msg: S) -> Self::Future {
        // This should equal to "Hello, World!" in this example
        assert_eq!(msg.to_string(), "Hello, World!");
        print!("{}", msg);
        ok(())
    }
}

let p = Print;
let ef = EchoFactory;
// `e` would be the pipe: `Echo` > `Print`
let e = ef.new_handler(p).await?;
// this would print "Hello, World!" to stdout
e.call("Hello, World!").await?;
```

</p>
</details>

would be same as:

```rust
async fn echo<T>(t: T) -> Result<T, ()> {
    Ok(t)
}

async fn print<T: Display>(t: T) -> Result<(), ()> {
    print!("{}", t);
    Ok(())
}

// `e` would be the pipe: `echo` > `print`
let e = apply!(echo, print);
// since echo just pass the message, below is possible
let e = apply!(echo, echo, echo, print);
// this would print "Hello, World" to stdout
e.call("Hello, World!").await?;

```

### CODE REVIEW

**Review by minchurl — APPROVED** [review]

**Review by minchurl — APPROVED** [review]
.

**Review by minchurl — DISMISSED** [review]
I checked all new tests in fn_pipe.rs and pipe.rs.

Since I'm still not good at rust, I can't check the detail part of fn_pipe.rs. However, I approve it as soon as possible because I think fast-PR is good to @buttercrab .

Also, I will review the logic of fn_pipe.rs as soon as possible.

P.S. Sorry for the re-review request. It is my fault. orz

**Review by utilForever — DISMISSED** [review]
LGTM now. Thanks for your work! 🤝

**Review by minchurl — APPROVED** [review]
you must not request too many times.

**Review by utilForever — APPROVED** [review]
Good to go~ 🚌

**Pull request merged**
